apply plugin: 'io.spring.convention.spring-module'

dependencies {
	compile 'io.projectreactor:reactor-bom:Bismuth-SR17'
	compile 'org.springframework:spring-framework-bom:5.0.19.RELEASE'
	compile 'org.springframework.data:spring-data-releasetrain:Kay-SR14'
	optional 'org.springframework:spring-jcl'
	optional 'org.bouncycastle:bcpkix-jdk15on'
}

repositories{
	mavenCentral()
	gradlePluginPortal()
	jcenter()
	maven { url 'https://repo.spring.io/plugins-snapshot' }
	maven {
		name = "jfreleases"
		url = "https://releases.jfrog.io/artifactory/oss-releases/"
	}
}
