apply plugin: 'io.spring.convention.spring-module'

dependencies {
	compile project(':spring-security-core')
	compile springCoreDependency
	compile 'org.springframework:spring-aop'
	compile 'org.springframework:spring-beans'
	compile 'org.springframework:spring-context'
	compile 'org.springframework:spring-expression'
	compile 'org.springframework:spring-web'
	compile 'io.projectreactor:reactor-bom:Bismuth-SR17'
	compile 'org.springframework:spring-framework-bom:5.0.19.RELEASE'
	compile 'org.springframework.data:spring-data-releasetrain:Kay-SR14'

	optional 'com.fasterxml.jackson.core:jackson-databind'
//	optional 'io.projectreactor:reactor-core'
	optional 'org.springframework:spring-jdbc'
	optional 'org.springframework:spring-tx'
	optional 'org.springframework:spring-webflux'
	optional 'org.springframework:spring-webmvc'

	provided 'javax.servlet:javax.servlet-api'

	testCompile project(path: ':spring-security-core', configuration: 'tests')
	testCompile 'commons-codec:commons-codec'
	testCompile 'io.projectreactor:reactor-test'
	testCompile 'javax.xml.bind:jaxb-api'
	testCompile 'org.codehaus.groovy:groovy-all'
	testCompile 'org.skyscreamer:jsonassert'
	testCompile 'org.springframework:spring-webflux'
	testCompile powerMock2Dependencies
	testCompile spockDependencies

	testRuntime 'org.hsqldb:hsqldb'
}
repositories{
	mavenCentral()
	gradlePluginPortal()
	jcenter()
	maven { url 'https://repo.spring.io/plugins-snapshot' }
	maven {
		name = "jfreleases"
		url = "https://releases.jfrog.io/artifactory/oss-releases/"
	}
}

